# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'CalorieCounterApp' do

  # Pods for CalorieCounterApp
  #pod "ConcentricProgressRingView"
  #pod 'PNChartSwift', :git => 'https://github.com/YichenZhou/PNChart-Swift'

end
